---
title: "Counts analisys"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(PEPI)
library(cmdstanr)
library(rstan)
library(dplyr)
library(ggplot2)
```

We load a time series of cell counts generated with rRACES

```{r}
set.seed(2010)
counts
```

We create a PEPI object of counts type
```{r}

x = init_counts(counts)
x
```


We fit cell counts 
```{r}

x = fit_counts(
  x,
  path_to_model = "models",
  cmdstan_path = cmdstanr::cmdstan_path(),
  ndraws = 1000,
  init = list(
    list(
      lambda_minus = 5,
      lambda_plus = 8,
      effective_switch_rate_n = 0.7,
      effective_switch_rate_p = 0.8
    )
  ),
  seed = 215,
  alpha_ln = 1000,
  beta_ln = 1000,
  alpha_lp = 1200,
  beta_lp = 1000,
  alpha_rn = 100,
  beta_rn = 200,
  alpha_rp = 100,
  beta_rp = 200
)

x
```



We get and plot average counts 
```{r}

x = get_average_counts(x)
plot_counts(x)

```


We plot the posterior of growth rates and effective switching rates
```{r}

x = get_posterior(x)
x = get_prior(x,model_types = c("counts"))
plot_inference(x,params = c("lambda_minus","lambda_plus","effective_switch_rate_n","effective_switch_rate_p"))
```

